### PR TITLE
fix: update hapi

### LINKED ISSUE #172: Upgrade Hapi
For security and performance reasons and also because when installing this module it now logs a bunch of disconcerting warning messages as seen here https://github.com/ipfs/js-ipfs/issues/2008

### PR DESCRIPTION
**Pull request by vasco-santos**
For security and performance reasons, Hapi updated from v16 to v18. The hapi implementation moved from callbacks to promises and the code for the signaling server was refactored to use async await instead.

Moreover, in this PR I had to throw an error if metrics are enabled as the current implementation of `epimetheus` is not compatible with the new implementation of hapi. I created an issue to track this #174  

Closes #172

### CODE REVIEW

**Comment by vasco-santos** [comment]
@jacobheun I fixed `bin.js` and modified the commit message

File: src/sig-server/index.js [hunk 1]
```diff
@@ -1,56 +1,48 @@
...
+    handler: (request, reply) => reply.file(path.join(__dirname, 'index.html'), {
+      confine: false
     })
-
-    if (options.metrics) { epimetheus.instrument(http) }
   })
 
+  if (options.metrics) {
+    // TODO: reenable epimatheus when support
+    log('wait for epimeteus support')
```
Comment (jacobheun) [inline src/sig-server/index.js]:
```suggestion
    log('wait for epimetheus support')
```

File: src/sig-server/index.js [hunk 2]
```diff
@@ -1,56 +1,48 @@
...
+    path: '/',
+    handler: (request, reply) => reply.file(path.join(__dirname, 'index.html'), {
+      confine: false
     })
-
-    if (options.metrics) { epimetheus.instrument(http) }
   })
 
+  if (options.metrics) {
+    // TODO: reenable epimatheus when support
```
Comment (jacobheun) [inline src/sig-server/index.js]:
```suggestion
    // TODO: reenable epimetheus when support
```

File: src/sig-server/index.js [hunk 3]
```diff
@@ -1,56 +1,48 @@
...
+    log('wait for epimeteus support')
+    throw new Error('epimeteus is currently not supported by hapi. Needs: https://github.com/libp2p/js-libp2p-webrtc-star/issues/174')
```
Comment (jacobheun) [inline src/sig-server/index.js]:
```suggestion
    throw new Error('epimetheus is currently not supported by hapi. Needs: https://github.com/libp2p/js-libp2p-webrtc-star/issues/174')
```
